---
title: "JP Morgan's Complaints Received"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(lubridate)
library(janitor)
library(readxl)
library(writexl)

complaints_raw <- readRDS("~/Desktop/R_MiniProject_Ashwath/miniproject/complaints.rds")

allcomplaints <- complaints_raw %>%
  clean_names()

```

Column {data-width=650}
-----------------------------------------------------------------------

Analyzing JP Morgan's Complaints Received

```{r}

jpmorgan <- allcomplaints%>%
  filter(company == "JPMORGAN CHASE & CO.")

jpmorgan %>%
  count(product, sort = TRUE)


```

Column {data-width=350}
-----------------------------------------------------------------------

Understanding when in the year JP Morgan receives the most complaints.

```{r}

complaintsbymonth <- jpmorgan %>%
  group_by(month = month(date_received)) %>%
  summarise(nummonths = n())

complaintsbymonth

ggplot(complaintsbymonth, aes(x = month, y = nummonths)) + 
  geom_line()

```

Grouping complaints by month and the way they were submitted.

```{r}

month_submissiontype <-  jpmorgan %>% 
  group_by(month = month(date_received), submitted_via) %>% 
  summarise(nummonths = n())


ggplot(month_submissiontype) +
  # add bar for each month colored by submission type
  geom_bar(aes(x = month, y = nummonths, fill = submitted_via),
           stat = "identity", position = "dodge") 

```

